version: 2
jobs:
  build:
    working_directory: ~/my-project
    docker:
      - image: circleci/android:api-28-node
    steps:
      - checkout
      - run:
          name: Install Nativescript
          command: npm i -g nativescript --ignore-scripts --unsafe-perm --no-progress;
      - restore_cache:
          key: my-project-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm install --no-progress
      - save_cache:
          key: my-project-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"  
      - run:
          name: "Prepare Android"
          command: |
            tns platform add android  