version: 2
jobs:
  build:
    working_directory: ~/my-project
    docker:
      - image: circleci/android:api-28-node
    environment:
      ANDROID_IMAGE: system-images;android-25;default;x86_64  
    steps:
      - checkout
      - run:
          name: Install Nativescript
          command: sudo npm i -g nativescript --ignore-scripts --unsafe-perm --no-progress;
      - restore_cache:
          key: my-project-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm install --no-progress
      - save_cache:
          key: my-project-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"  
      - run:
          name: "Prepare Android"
          command: |
            tns platform add android  

      - run:
          name: Lists installed targets
          command: android list target
          environment:
          TERM: dumb
      - run:
          name: Show list of system-images
          command: sdkmanager --list --verbose | grep system-images
      - run:
          name: Setup Emulator
          command: sdkmanager "system-images;android-28;google_apis;x86_64" && echo "no" | avdmanager create avd -n test -k "system-images;android-28;google_apis;x86_64"
      - run:
          name: Show list of acailable devices
          command: tns device android --available-devices
      
          # - run:
      #     name: Launch Emulator
      #     command: |
      #             cd ${ANDROID_HOME}/emulator;ls
      #             export LD_LIBRARY_PATH=${ANDROID_HOME}/emulator/lib64:${ANDROID_HOME}/emulator/lib64/qt/lib
      #             emulator -avd test -no-window -noaudio -no-boot-anim -no-window -accel on
      #     background: true
      # - run:
      #     name: Wait emulator
      #     command: |
      #         circle-android wait-for-boot
      #         adb shell input keyevent 82
      - run:
          name: "Run Tests"
          command: |
            tns test android --device test --justlaunch  
         